"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./page.module.css";
function buildTree(paths){const root=[];for(const p of paths){const parts=p.split("/");let level=root;parts.forEach((name,i)=>{let x=level.find(v=>v.name===name);if(!x){x={name,path:parts.slice(0,i+1).join("/"),dir:i<parts.length-1,children:[]};level.push(x)}level=x.children})}return root}
function Tree({items,active,onOpen,depth=0}){return <>{items.sort((a,b)=>Number(b.dir)-Number(a.dir)||a.name.localeCompare(b.name)).map(x=><div key={x.path}><button className={x.path===active?styles.treeItem+" "+styles.selected:styles.treeItem} style={{paddingLeft:12+depth*16}} onClick={()=>!x.dir&&onOpen(x.path)}><span>{x.dir?"▸":"▱"}</span><span>{x.name}</span></button>{x.dir&&<Tree items={x.children} active={active} onOpen={onOpen} depth={depth+1}/>}</div>)}</>}
export default function Home(){
 const [status,setStatus]=useState("connecting"),[terminal,setTerminal]=useState(""),[files,setFiles]=useState([]),[active,setActive]=useState("README.md"),[code,setCode]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[panel,setPanel]=useState("editor"),[preview,setPreview]=useState(false);
 const tree=useMemo(()=>buildTree(files.map(x=>x.path)),[files]);
 async function loadFiles(){try{const r=await fetch("/api/workspace",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setFiles(d.files||[]);setStatus("connected")}catch{setStatus("error")}}
 async function openFile(path){setBusy(true);setActive(path);try{const r=await fetch("/api/workspace?path="+encodeURIComponent(path),{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gagal membaca file");setCode(d.content||"");setDirty(false);setPanel("editor");setMenu(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function save(){if(!active)return;setBusy(true);try{const r=await fetch("/api/workspace",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({path:active,content:code})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gagal menyimpan");setDirty(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function connect(){setStatus("connecting");try{const r=await fetch("/api/sandbox",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);setTerminal(d.terminalUrl);setStatus("connected")}catch{setStatus("error")}}
 useEffect(()=>{loadFiles();connect()},[]);useEffect(()=>{if(active)openFile(active)},[]);
 return <main className={styles.shell}><header className={styles.topbar}><button className={styles.menuBtn} onClick={()=>setMenu(v=>!v)}>☰</button><div className={styles.brand}><strong>⚡ Mobile Code</strong><span>{active||"No file"}</span></div><div className={styles.actions}><button className={styles.run} onClick={()=>setPreview(v=>!v)}>{preview?"×":"⚡"}</button><button className={styles.save} onClick={save} disabled={!dirty||busy}>{busy?"…":"Save"}</button></div></header>
 <div className={styles.body}><aside className={menu?styles.sidebar+" "+styles.open:styles.sidebar}><div className={styles.projectHead}><span>PROJECT</span><div><button onClick={()=>{loadFiles();connect()}}>↻</button><button onClick={()=>setMenu(false)}>×</button></div></div><div className={styles.path}>/vercel/sandbox/workspace</div><div className={styles.tree}>{files.length?<Tree items={tree} active={active} onOpen={openFile}/>:<div className={styles.loading}>Loading workspace…</div>}</div><div className={styles.sideBottom}><i className={status==="connected"?styles.dot:styles.dotOff}></i>{status}</div></aside>
 <section className={styles.main}><div className={styles.editorHead}><span>▱ {active||"No file"}</span><span>{dirty?"●":""}</span></div>{preview?<div className={styles.preview}><iframe srcDoc={active?.endsWith(".html")?code:""} title="Live Preview"/></div>:<div className={styles.editor}><textarea value={code} onChange={e=>{setCode(e.target.value);setDirty(true)}} spellCheck={false} autoCapitalize="off" autoCorrect="off"/></div>}<section className={panel==="terminal"?styles.terminal:styles.terminal+" "+styles.termHidden}><div className={styles.termHead}><b>TERMINAL</b><button onClick={()=>terminal&&window.open(terminal,"_blank")}>Open full ↗</button></div>{terminal?<iframe src={terminal} title="Linux Terminal"/>:<div className={styles.termEmpty}>Connecting to cloud Linux…</div>}</section></section></div>
 <nav className={styles.bottomNav}><button className={panel==="editor"?styles.navActive:""} onClick={()=>{setPanel("editor");setPreview(false)}}>⌘ Editor</button><button className={menu?styles.navActive:""} onClick={()=>setMenu(v=>!v)}>☰ Files</button><button className={panel==="terminal"?styles.navActive:""} onClick={()=>setPanel("terminal")}>▣ Terminal</button></nav></main>}
